### ISSUE TITLE
when I build on ubuntu, crypto handshake timeout,please  which reason???

### ISSUE THREAD

**Issue by InnerCalmer** [qdeconinck/mp-quic#25]
$go run example/client/main.go https://clemente.io

GET https://clemente.io
Starting new connection to clemente.io ([::]:36759 -> 18.65.116.106:443), connectionID fae96b208619c577, version 512
Closing session with error: HandshakeTimeout: Crypto handshake did not complete in time.
Connection fae96b208619c577 closed.
panic: Get https://clemente.io: HandshakeTimeout: Crypto handshake did not complete in time.

goroutine 5 [running]:
main.main.func1(0xc420067290, 0xc420012660, 0x7ffceead91f1, 0x13)
	/home/frank/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:56 +0x312
created by main.main
	/home/frank/go/src/github.com/lucas-clemente/quic-go/example/client/main.go:53 +0x332
exit status 2

**Comment by InnerCalmer** [comment]
I build on ubuntu

**Comment by mainrs** [comment]
Did you manage to solve this or found the issue?
